name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3  
      - name: Build app
        run: ci/build-app.sh
      - name: Test
        run : chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v3  
        with:
          name: code 
          path: .